person:
  id: 1
  name: wuzhxiaun
  hobby:
    - 吃饭
    - 睡觉
    - 打豆豆
  map:
    k1: v1
    k2: v2
  pet:
    type: dog
    name: 旺财
  family: [father,mother]


student:
  name: wuzhixan


randomm:
  value: ${random.value} // 随机数
  number: ${random.int}
  longNum: ${random.long}
  uuid: ${random.uuid}
  lessThan10: ${random.int(10)}
  rangge: ${random.int(100,2000)}
